apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
